blueprint:
  name: Flic Button - Simple Toggle
  description: |
    Toggle any entity (light, switch, etc.) with a Flic button.

    - **Single press**: Toggle the target entity
    - **Double press**: Turn entity on at full brightness (optional)
    - **Long press**: Turn entity off (optional)

  domain: automation

  input:
    flic_button:
      name: Flic Button
      description: The Flic button to use
      selector:
        device:
          integration: flic_ble

    target_entity:
      name: Target Entity
      description: The entity to control (light, switch, etc.)
      selector:
        entity:
          domain:
            - light
            - switch
            - fan
            - media_player

    single_press_action:
      name: Single Press Action
      description: Action for single press
      default: toggle
      selector:
        select:
          options:
            - label: Toggle
              value: toggle
            - label: Turn On
              value: turn_on
            - label: Turn Off
              value: turn_off

    enable_double_press:
      name: Enable Double Press
      description: Enable double press action (turn on at full brightness)
      default: false
      selector:
        boolean:

    enable_long_press:
      name: Enable Long Press
      description: Enable long press action (turn off)
      default: false
      selector:
        boolean:

mode: restart
max_exceeded: silent

trigger:
  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_short_press
    id: single_press

  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_double_press
    id: double_press
    enabled: !input enable_double_press

  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_long_press
    id: long_press
    enabled: !input enable_long_press

action:
  - choose:
      # Single press
      - conditions:
          - condition: trigger
            id: single_press
        sequence:
          - choose:
              - conditions: "{{ single_press_action == 'toggle' }}"
                sequence:
                  - service: homeassistant.toggle
                    target:
                      entity_id: !input target_entity

              - conditions: "{{ single_press_action == 'turn_on' }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input target_entity

              - conditions: "{{ single_press_action == 'turn_off' }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: !input target_entity

      # Double press - full brightness
      - conditions:
          - condition: trigger
            id: double_press
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input target_entity
            data:
              brightness_pct: 100

      # Long press - turn off
      - conditions:
          - condition: trigger
            id: long_press
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input target_entity
