blueprint:
  name: Flic Button - Notification & Alert Control
  description: |
    Use a Flic button for quick notifications, alerts, or emergency actions.

    - **Single press**: Send notification
    - **Double press**: Trigger script or scene
    - **Long press**: Emergency action (panic button)

    Perfect for:
    - Panic button
    - "I'm home" notification
    - Quick status updates
    - Alert acknowledgment

  domain: automation

  input:
    flic_button:
      name: Flic Button
      description: The Flic button to use
      selector:
        device:
          integration: flic_ble

    enable_single_press_notification:
      name: Enable Single Press Notification
      description: Send notification on single press
      default: true
      selector:
        boolean:

    notification_service:
      name: Notification Service
      description: Notification service to use (e.g., notify.mobile_app_iphone)
      default: notify.notify
      selector:
        text:

    notification_title:
      name: Notification Title
      description: Title of the notification
      default: Flic Button Pressed
      selector:
        text:

    notification_message:
      name: Notification Message
      description: Message to send
      default: Button was pressed at {{ now().strftime('%H:%M:%S') }}
      selector:
        text:
          multiline: true

    enable_double_press_action:
      name: Enable Double Press Action
      description: Run script/scene on double press
      default: false
      selector:
        boolean:

    double_press_action:
      name: Double Press Action
      description: Action to perform on double press
      default: []
      selector:
        action:

    enable_long_press_emergency:
      name: Enable Long Press Emergency Action
      description: Trigger emergency action on long press (panic button)
      default: false
      selector:
        boolean:

    emergency_action:
      name: Emergency Action
      description: Emergency action to perform on long press
      default: []
      selector:
        action:

    emergency_notification:
      name: Send Emergency Notification
      description: Also send emergency notification
      default: true
      selector:
        boolean:

    emergency_message:
      name: Emergency Notification Message
      description: Emergency notification message
      default: "⚠️ EMERGENCY: Panic button pressed at {{ now().strftime('%H:%M:%S') }}"
      selector:
        text:

mode: restart
max_exceeded: silent

trigger:
  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_short_press
    id: single_press
    enabled: !input enable_single_press_notification

  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_double_press
    id: double_press
    enabled: !input enable_double_press_action

  - platform: device
    domain: flic_ble
    device_id: !input flic_button
    type: button_long_press
    id: emergency
    enabled: !input enable_long_press_emergency

action:
  - choose:
      # Single press - notification
      - conditions:
          - condition: trigger
            id: single_press
        sequence:
          - service: !input notification_service
            data:
              title: !input notification_title
              message: !input notification_message

      # Double press - custom action
      - conditions:
          - condition: trigger
            id: double_press
        sequence: !input double_press_action

      # Long press - emergency
      - conditions:
          - condition: trigger
            id: emergency
        sequence:
          - if:
              - condition: template
                value_template: !input emergency_notification
            then:
              - service: !input notification_service
                data:
                  title: "🚨 EMERGENCY ALERT"
                  message: !input emergency_message
                  data:
                    priority: high
                    ttl: 0
                    channel: alarm_stream

          - choose: []
            default: !input emergency_action
